### ISSUE TITLE
Weird format returned from the API

### ISSUE THREAD

**Issue by chenliu0831** [brettlangdon/node-dogapi#41]
Getting the following points with the query API for a metrics query.

```
[[1460670060000,{"s":1,"e":0,"c":[8,6,6,6,6,6,6,9,8,4,5,5,8,1,0,5,5]}]]
```

Is this related to this lib?

**Comment by brettlangdon** [comment]
@chenliu0831 Yes it is. The problem is that this package has to use [json-bigint](http://npmjs.com/package/json-bigint) to parse the json responses from Datadog. The reason is that some of the integer values from datadog have become large than the largest number supported by JSON, so the numbers would overflow and become negative values. For example, this was first an issue with event ids.

For reference the number format is from [bignumber.js](https://www.npmjs.com/package/bignumber.js)


Please let me know if I can be of any other assistance.

**Comment by chenliu0831** [comment]
@brettlangdon Got it. Thanks a lot.
